part of 'button.dart';

class PmsIconButton {
  static IconButton primary(
    BuildContext context, {
    Key? key,
    VisualDensity? visualDensity,
    // EdgeInsetsGeometry? padding,
    AlignmentGeometry? alignment,
    double? splashRadius,
    required Widget icon,
    // Color? focusColor,
    // Color? hoverColor,
    // Color? color,
    // Color? splashColor,
    // Color? highlightColor,
    // Color? disabledColor,
    required VoidCallback? onPressed,
    ValueChanged<bool>? onHover,
    VoidCallback? onLongPress,
    MouseCursor? mouseCursor,
    FocusNode? focusNode,
    bool autofocus = false,
    String? tooltip,
    bool? enableFeedback,
    BoxConstraints? constraints,
    ButtonStyle? style,
    bool? isSelected,
    Widget? selectedIcon,
    WidgetStatesController? statesController,
    ButtonSize size = ButtonSize.small,
  }) {
    return IconButton(
      key: key,
      iconSize: size.iconSize,
      visualDensity: visualDensity,
      alignment: alignment,
      splashRadius: splashRadius,
      // color:color,
      // focusColor:focusColor,
      // hoverColor:hoverColor,
      // highlightColor:highlightColor,
      // splashColor:splashColor,
      // disabledColor:disabledColor,
      onPressed: onPressed,
      onHover: onHover,
      onLongPress: onLongPress,
      mouseCursor: mouseCursor,
      focusNode: focusNode,
      autofocus: autofocus,
      tooltip: tooltip,
      enableFeedback: enableFeedback,
      constraints: constraints,
      style: ButtonStyleHelper.primaryIcon(context, size: size),
      isSelected: isSelected,
      selectedIcon: selectedIcon,
      statesController: statesController,
      icon: icon,
    );
  }

  static IconButton secondary(
    BuildContext context, {
    Key? key,
    VisualDensity? visualDensity,
    // EdgeInsetsGeometry? padding,
    AlignmentGeometry? alignment,
    double? splashRadius,
    required Widget icon,
    // Color? focusColor,
    // Color? hoverColor,
    // Color? color,
    // Color? splashColor,
    // Color? highlightColor,
    // Color? disabledColor,
    required VoidCallback? onPressed,
    ValueChanged<bool>? onHover,
    VoidCallback? onLongPress,
    MouseCursor? mouseCursor,
    FocusNode? focusNode,
    bool autofocus = false,
    String? tooltip,
    bool? enableFeedback,
    BoxConstraints? constraints,
    ButtonStyle? style,
    bool? isSelected,
    Widget? selectedIcon,
    WidgetStatesController? statesController,
    ButtonSize size = ButtonSize.small,
  }) {
    return IconButton(
      key: key,
      iconSize: size.iconSize,
      visualDensity: visualDensity,
      alignment: alignment,
      splashRadius: splashRadius,
      // color:color,
      // focusColor:focusColor,
      // hoverColor:hoverColor,
      // highlightColor:highlightColor,
      // splashColor:splashColor,
      // disabledColor:disabledColor,
      onPressed: onPressed,
      onHover: onHover,
      onLongPress: onLongPress,
      mouseCursor: mouseCursor,
      focusNode: focusNode,
      autofocus: autofocus,
      tooltip: tooltip,
      enableFeedback: enableFeedback,
      constraints: constraints,
      style: ButtonStyleHelper.secondaryIcon(context, size: size),
      isSelected: isSelected,
      selectedIcon: selectedIcon,
      statesController: statesController,
      icon: icon,
    );
  }

  static IconButton tertiary(
    BuildContext context, {
    Key? key,
    VisualDensity? visualDensity,
    // EdgeInsetsGeometry? padding,
    AlignmentGeometry? alignment,
    double? splashRadius,
    required Widget icon,
    // Color? focusColor,
    // Color? hoverColor,
    // Color? color,
    // Color? splashColor,
    // Color? highlightColor,
    // Color? disabledColor,
    required VoidCallback? onPressed,
    ValueChanged<bool>? onHover,
    VoidCallback? onLongPress,
    MouseCursor? mouseCursor,
    FocusNode? focusNode,
    bool autofocus = false,
    String? tooltip,
    bool? enableFeedback,
    BoxConstraints? constraints,
    ButtonStyle? style,
    bool? isSelected,
    Widget? selectedIcon,
    WidgetStatesController? statesController,
    ButtonSize size = ButtonSize.small,
  }) {
    return IconButton(
      key: key,
      iconSize: size.iconSize,
      visualDensity: visualDensity,
      alignment: alignment,
      splashRadius: splashRadius,
      // color:color,
      // focusColor:focusColor,
      // hoverColor:hoverColor,
      // highlightColor:highlightColor,
      // splashColor:splashColor,
      // disabledColor:disabledColor,
      onPressed: onPressed,
      onHover: onHover,
      onLongPress: onLongPress,
      mouseCursor: mouseCursor,
      focusNode: focusNode,
      autofocus: autofocus,
      tooltip: tooltip,
      enableFeedback: enableFeedback,
      constraints: constraints,
      style: ButtonStyleHelper.tertiaryIcon(context, size: size),
      isSelected: isSelected,
      selectedIcon: selectedIcon,
      statesController: statesController,
      icon: icon,
    );
  }
}
