# staff_held_license_page画面 - Read(一覧取得クエリ、担当者→保有資格)
#
# 画面仕様: source/view.yaml #StaffHeldLicensePage(担当者起点、mstr_staff_license経由で
# mstr_licenseへ)。要件0045で新規追加。
#
# 要件0045レビュー: view.yamlの`holdeLicense`は元々内側に`from: mstr_license`の
# `licenses`という余分な入れ子層を持ち、mstr_staff_license自身の列
# (mstr_staff_license_id/info_staff_id)をmstr_license由来として重複宣言していた
# (LicenseHoldersPage.licensesとの対称性から判断したコピー&ペースト起因の構造ミス)。
# 1階層に平坦化して生成した。
#
# staff自身の列はstaff_page_read.graphqlと同型(住所無し)。license配下のlicense
# (mstr_license)はlicense_page_read.graphqlのnodesと同型。

query StaffHeldLicensePageRead(
  $first: Int!
  $offset: Int
  $filter: InfoStaffFilter = {}
  $orderBy: [InfoStaffsOrderBy!] = [PRIMARY_KEY_ASC]
  $languageCodeId: UUID!
  $removed: Boolean = false
) {
  allInfoStaffs(
    first: $first
    offset: $offset
    orderBy: $orderBy
    filter: { and: [{ remove: { equalTo: $removed } }, $filter] }
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      infoStaffId
      infoCompanyId
      code
      sex
      phone
      privatePhone
      symbol
      remarks
      updateAt
      remove

      labels: sharedAppellationByNames {
        sharedAppellationsId
        sharedDictionaryBySharedDictionaryNameId {
          sharedDictionaryId
          value: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $languageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
        }
        sharedDictionaryBySharedDictionaryPronunciationId {
          sharedDictionaryId
          value: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $languageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
        }
        sharedDictionaryBySharedDictionaryNicknameId {
          sharedDictionaryId
          value: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $languageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
        }
      }

      holdeLicense: mstrStaffLicensesByInfoStaffId(
        filter: { remove: { equalTo: false } }
      ) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          mstrStaffLicenseId
          infoStaffId
          mstrLicenseId
          startAt
          stopAt
          abeyance
          abeyanceAt
          revocation
          revocationAt

          license: mstrLicenseByMstrLicenseId {
            mstrLicenseId
            code
            detail
            publicLicense
            customerLicense
            organizationLicense
            updateInterval {
              years
              months
              days
              hours
              minutes
              seconds
            }
            symbol
            remarks
            updateAt
            remove

            labels: sharedAppellationByNames {
              sharedAppellationsId
              sharedDictionaryBySharedDictionaryNameId {
                sharedDictionaryId
                value: sharedDictionaryValuesBySharedDictionaryId(
                  condition: { sharedLanguageCodeId: $languageCodeId }
                ) {
                  nodes {
                    dictionaryValue
                  }
                }
              }
              sharedDictionaryBySharedDictionaryPronunciationId {
                sharedDictionaryId
                value: sharedDictionaryValuesBySharedDictionaryId(
                  condition: { sharedLanguageCodeId: $languageCodeId }
                ) {
                  nodes {
                    dictionaryValue
                  }
                }
              }
              sharedDictionaryBySharedDictionaryNicknameId {
                sharedDictionaryId
                value: sharedDictionaryValuesBySharedDictionaryId(
                  condition: { sharedLanguageCodeId: $languageCodeId }
                ) {
                  nodes {
                    dictionaryValue
                  }
                }
              }
            }

            update_user: historyInfoStaffByUpdateUserHistoryIdAndUpdateUserId {
              historyId
              infoStaffId
              infoCompanyId
              code
              sex
              phone
              symbol
              privatePhone
              name: sharedAppellationByNames {
                sharedAppellationsId
                sharedDictionaryBySharedDictionaryNameId {
                  sharedDictionaryId
                  value: sharedDictionaryValuesBySharedDictionaryId(
                    condition: { sharedLanguageCodeId: $languageCodeId }
                  ) {
                    nodes {
                      dictionaryValue
                    }
                  }
                }
                sharedDictionaryBySharedDictionaryPronunciationId {
                  sharedDictionaryId
                  value: sharedDictionaryValuesBySharedDictionaryId(
                    condition: { sharedLanguageCodeId: $languageCodeId }
                  ) {
                    nodes {
                      dictionaryValue
                    }
                  }
                }
                sharedDictionaryBySharedDictionaryNicknameId {
                  sharedDictionaryId
                  value: sharedDictionaryValuesBySharedDictionaryId(
                    condition: { sharedLanguageCodeId: $languageCodeId }
                  ) {
                    nodes {
                      dictionaryValue
                    }
                  }
                }
              }
            }
          }
        }
      }

      update_user: historyInfoStaffByUpdateUserHistoryIdAndUpdateUserId {
        historyId
        infoStaffId
        infoCompanyId
        code
        sex
        phone
        symbol
        privatePhone
        name: sharedAppellationByNames {
          sharedAppellationsId
          sharedDictionaryBySharedDictionaryNameId {
            sharedDictionaryId
            value: sharedDictionaryValuesBySharedDictionaryId(
              condition: { sharedLanguageCodeId: $languageCodeId }
            ) {
              nodes {
                dictionaryValue
              }
            }
          }
          sharedDictionaryBySharedDictionaryPronunciationId {
            sharedDictionaryId
            value: sharedDictionaryValuesBySharedDictionaryId(
              condition: { sharedLanguageCodeId: $languageCodeId }
            ) {
              nodes {
                dictionaryValue
              }
            }
          }
          sharedDictionaryBySharedDictionaryNicknameId {
            sharedDictionaryId
            value: sharedDictionaryValuesBySharedDictionaryId(
              condition: { sharedLanguageCodeId: $languageCodeId }
            ) {
              nodes {
                dictionaryValue
              }
            }
          }
        }
      }
    }
  }
}
