# license_holders_page画面 - Read(一覧取得クエリ、資格→保有担当者)
#
# 画面仕様: source/view.yaml #LicenseHoldersPage(資格起点、mstr_staff_license経由で
# info_staffへ)。要件0045で新規追加。
#
# 要件0045レビュー: view.yamlの`licenses`(mstr_license(1)→mstr_staff_license(多))は
# 元はarrayType: toFirstOne、内側の`staff`(junction行(1)→info_staff(1))は
# arrayType: toManyと基数が入れ替わっていた。schema.jsonの方針(基数の妥当性は生成側の
# 責務)に従い、生成時にtoMany/toFirstOneを入れ替えて修正した。
#
# license配下のlicense(mstr_license自身への自己参照、親と同一レコード)は
# StaffLicenseEdit系のstaff/license対称埋め込みパターンにあわせてview.yaml通りに
# 生成している(冗長だが誤りではない)。staff(mstr_staff_license.staff)は
# staff_page_read.graphqlと同型(住所無し)。

query LicenseHoldersPageRead(
  $first: Int!
  $offset: Int
  $filter: MstrLicenseFilter = {}
  $orderBy: [MstrLicensesOrderBy!] = [PRIMARY_KEY_ASC]
  $languageCodeId: UUID!
  $removed: Boolean = false
) {
  allMstrLicenses(
    first: $first
    offset: $offset
    orderBy: $orderBy
    filter: { and: [{ remove: { equalTo: $removed } }, $filter] }
  ) {
    totalCount
    pageInfo {
      hasNextPage
      endCursor
    }
    nodes {
      mstrLicenseId
      code
      detail
      publicLicense
      customerLicense
      organizationLicense
      updateInterval {
        years
        months
        days
        hours
        minutes
        seconds
      }
      symbol
      remarks
      updateAt
      remove

      labels: sharedAppellationByNames {
        sharedAppellationsId
        sharedDictionaryBySharedDictionaryNameId {
          sharedDictionaryId
          value: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $languageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
        }
        sharedDictionaryBySharedDictionaryPronunciationId {
          sharedDictionaryId
          value: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $languageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
        }
        sharedDictionaryBySharedDictionaryNicknameId {
          sharedDictionaryId
          value: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $languageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
        }
      }

      licenses: mstrStaffLicensesByMstrLicenseId(
        filter: { remove: { equalTo: false } }
      ) {
        totalCount
        pageInfo {
          hasNextPage
          endCursor
        }
        nodes {
          mstrStaffLicenseId
          infoStaffId
          mstrLicenseId
          startAt
          stopAt
          abeyance
          abeyanceAt
          revocation
          revocationAt

          staff: infoStaffByInfoStaffId {
            infoStaffId
            infoCompanyId
            code
            sex
            phone
            privatePhone
            symbol
            remarks
            updateAt
            remove

            labels: sharedAppellationByNames {
              sharedAppellationsId
              sharedDictionaryBySharedDictionaryNameId {
                sharedDictionaryId
                value: sharedDictionaryValuesBySharedDictionaryId(
                  condition: { sharedLanguageCodeId: $languageCodeId }
                ) {
                  nodes {
                    dictionaryValue
                  }
                }
              }
              sharedDictionaryBySharedDictionaryPronunciationId {
                sharedDictionaryId
                value: sharedDictionaryValuesBySharedDictionaryId(
                  condition: { sharedLanguageCodeId: $languageCodeId }
                ) {
                  nodes {
                    dictionaryValue
                  }
                }
              }
              sharedDictionaryBySharedDictionaryNicknameId {
                sharedDictionaryId
                value: sharedDictionaryValuesBySharedDictionaryId(
                  condition: { sharedLanguageCodeId: $languageCodeId }
                ) {
                  nodes {
                    dictionaryValue
                  }
                }
              }
            }

            update_user: historyInfoStaffByUpdateUserHistoryIdAndUpdateUserId {
              historyId
              infoStaffId
              infoCompanyId
              code
              sex
              phone
              symbol
              privatePhone
              name: sharedAppellationByNames {
                sharedAppellationsId
                sharedDictionaryBySharedDictionaryNameId {
                  sharedDictionaryId
                  value: sharedDictionaryValuesBySharedDictionaryId(
                    condition: { sharedLanguageCodeId: $languageCodeId }
                  ) {
                    nodes {
                      dictionaryValue
                    }
                  }
                }
                sharedDictionaryBySharedDictionaryPronunciationId {
                  sharedDictionaryId
                  value: sharedDictionaryValuesBySharedDictionaryId(
                    condition: { sharedLanguageCodeId: $languageCodeId }
                  ) {
                    nodes {
                      dictionaryValue
                    }
                  }
                }
                sharedDictionaryBySharedDictionaryNicknameId {
                  sharedDictionaryId
                  value: sharedDictionaryValuesBySharedDictionaryId(
                    condition: { sharedLanguageCodeId: $languageCodeId }
                  ) {
                    nodes {
                      dictionaryValue
                    }
                  }
                }
              }
            }
          }

          license: mstrLicenseByMstrLicenseId {
            mstrLicenseId
            code
            detail
            publicLicense
            customerLicense
            organizationLicense
            updateInterval {
              years
              months
              days
              hours
              minutes
              seconds
            }
            symbol
            remarks
            updateAt
            remove

            labels: sharedAppellationByNames {
              sharedAppellationsId
              sharedDictionaryBySharedDictionaryNameId {
                sharedDictionaryId
                value: sharedDictionaryValuesBySharedDictionaryId(
                  condition: { sharedLanguageCodeId: $languageCodeId }
                ) {
                  nodes {
                    dictionaryValue
                  }
                }
              }
              sharedDictionaryBySharedDictionaryPronunciationId {
                sharedDictionaryId
                value: sharedDictionaryValuesBySharedDictionaryId(
                  condition: { sharedLanguageCodeId: $languageCodeId }
                ) {
                  nodes {
                    dictionaryValue
                  }
                }
              }
              sharedDictionaryBySharedDictionaryNicknameId {
                sharedDictionaryId
                value: sharedDictionaryValuesBySharedDictionaryId(
                  condition: { sharedLanguageCodeId: $languageCodeId }
                ) {
                  nodes {
                    dictionaryValue
                  }
                }
              }
            }

            update_user: historyInfoStaffByUpdateUserHistoryIdAndUpdateUserId {
              historyId
              infoStaffId
              infoCompanyId
              code
              sex
              phone
              symbol
              privatePhone
              name: sharedAppellationByNames {
                sharedAppellationsId
                sharedDictionaryBySharedDictionaryNameId {
                  sharedDictionaryId
                  value: sharedDictionaryValuesBySharedDictionaryId(
                    condition: { sharedLanguageCodeId: $languageCodeId }
                  ) {
                    nodes {
                      dictionaryValue
                    }
                  }
                }
                sharedDictionaryBySharedDictionaryPronunciationId {
                  sharedDictionaryId
                  value: sharedDictionaryValuesBySharedDictionaryId(
                    condition: { sharedLanguageCodeId: $languageCodeId }
                  ) {
                    nodes {
                      dictionaryValue
                    }
                  }
                }
                sharedDictionaryBySharedDictionaryNicknameId {
                  sharedDictionaryId
                  value: sharedDictionaryValuesBySharedDictionaryId(
                    condition: { sharedLanguageCodeId: $languageCodeId }
                  ) {
                    nodes {
                      dictionaryValue
                    }
                  }
                }
              }
            }
          }
        }
      }

      update_user: historyInfoStaffByUpdateUserHistoryIdAndUpdateUserId {
        historyId
        infoStaffId
        infoCompanyId
        code
        sex
        phone
        symbol
        privatePhone
        name: sharedAppellationByNames {
          sharedAppellationsId
          sharedDictionaryBySharedDictionaryNameId {
            sharedDictionaryId
            value: sharedDictionaryValuesBySharedDictionaryId(
              condition: { sharedLanguageCodeId: $languageCodeId }
            ) {
              nodes {
                dictionaryValue
              }
            }
          }
          sharedDictionaryBySharedDictionaryPronunciationId {
            sharedDictionaryId
            value: sharedDictionaryValuesBySharedDictionaryId(
              condition: { sharedLanguageCodeId: $languageCodeId }
            ) {
              nodes {
                dictionaryValue
              }
            }
          }
          sharedDictionaryBySharedDictionaryNicknameId {
            sharedDictionaryId
            value: sharedDictionaryValuesBySharedDictionaryId(
              condition: { sharedLanguageCodeId: $languageCodeId }
            ) {
              nodes {
                dictionaryValue
              }
            }
          }
        }
      }
    }
  }
}
