# item_kind_page画面 - RFE(read for editing、要件0037: ItemKindPageEditのgenerateRfe: trueから導出)

query ItemKindPageRfe(
  $mstrItemKindId: UUID!
  $jaLanguageCodeId: UUID!
  $enLanguageCodeId: UUID!
) {
  mstrItemKindByMstrItemKindId(mstrItemKindId: $mstrItemKindId) {
    mstrItemKindId
    code
    remarks
    updateAt
    updateUserId
    updateUserHistoryId
    remove

    labels: sharedAppellationByNames {
      sharedAppellationsId
      sharedDictionaryBySharedDictionaryNameId {
        sharedDictionaryId
        ja: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $jaLanguageCodeId }
        ) {
          nodes {
            dictionaryValue
          }
        }
        en: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $enLanguageCodeId }
        ) {
          nodes {
            dictionaryValue
          }
        }
      }
      sharedDictionaryBySharedDictionaryPronunciationId {
        sharedDictionaryId
        ja: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $jaLanguageCodeId }
        ) {
          nodes {
            dictionaryValue
          }
        }
        en: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $enLanguageCodeId }
        ) {
          nodes {
            dictionaryValue
          }
        }
      }
      sharedDictionaryBySharedDictionaryNicknameId {
        sharedDictionaryId
        ja: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $jaLanguageCodeId }
        ) {
          nodes {
            dictionaryValue
          }
        }
        en: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $enLanguageCodeId }
        ) {
          nodes {
            dictionaryValue
          }
        }
      }
    }
  }
}
