# license_page画面 - RFE(read for editing、要件0037: LicensePageEditのgenerateRfe: trueから導出)

query LicensePageRfe(
  $mstrLicenseId: UUID!
  $ja: Boolean!
  $en: Boolean!
  $jaLanguageCodeId: UUID
  $enLanguageCodeId: UUID
) {
  mstrLicenseByMstrLicenseId(mstrLicenseId: $mstrLicenseId) {
    mstrLicenseId
    code
    detail
    publicLicense
    customerLicense
    organizationLicense
    updateInterval {
      years
      months
      days
      hours
      minutes
      seconds
    }
    remarks
    updateAt
    updateUserId
    updateUserHistoryId
    remove

    labels: sharedAppellationByNames {
      sharedAppellationsId
      sharedDictionaryBySharedDictionaryNameId {
        sharedDictionaryId
        ja: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $jaLanguageCodeId }
        ) @include(if: $ja) {
          nodes {
            dictionaryValue
          }
        }
        en: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $enLanguageCodeId }
        ) @include(if: $en) {
          nodes {
            dictionaryValue
          }
        }
      }
      sharedDictionaryBySharedDictionaryPronunciationId {
        sharedDictionaryId
        ja: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $jaLanguageCodeId }
        ) @include(if: $ja) {
          nodes {
            dictionaryValue
          }
        }
        en: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $enLanguageCodeId }
        ) @include(if: $en) {
          nodes {
            dictionaryValue
          }
        }
      }
      sharedDictionaryBySharedDictionaryNicknameId {
        sharedDictionaryId
        ja: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $jaLanguageCodeId }
        ) @include(if: $ja) {
          nodes {
            dictionaryValue
          }
        }
        en: sharedDictionaryValuesBySharedDictionaryId(
          condition: { sharedLanguageCodeId: $enLanguageCodeId }
        ) @include(if: $en) {
          nodes {
            dictionaryValue
          }
        }
      }
    }
  }
}
