targets:
  $default:
    sources:
      - test_hasura/**
    builders:
      graphql_codegen:
        options:
          schemaPath: 
            - "test_hasura/graphql/schema.graphql" #Typeやらの
            - "test_hasura/graphql/sort.graphql"
          assetsPath: test_hasura/**/*.graphql
          outputDirectory: "generated" #生成されたクラスの保管DIR
          clients: #ここが無いとOptionsが生成されない
            - graphql_flutter