targets:
  $default:
    builders:
      graphql_codegen:
        options:
          assetsPath: "lib/graphql/**.graphql" #graphqlsソース
          outputDirectory: "generated" #生成されたクラスの保管DIR
          schemaPath: "lib/graphql/schema.graphql" #Typeやらの
          clients: #ここが無いとOptionsが生成されない
            - graphql_flutterP