part of '../field.dart';

class PmsCheckboxField {
  static Widget primary({
    required BuildContext context,
    Key? key,
    required bool? value,
    required ValueChanged<bool?>? onChanged,
    MouseCursor? mouseCursor,
    Color? activeColor,
    // WidgetStateProperty<Color?>? fillColor,
    Color? checkColor,
    bool tristate = false,
    MaterialTapTargetSize? materialTapTargetSize,
    ty,
    Color? focusColor,
    Color? hoverColor,
    WidgetStateProperty<Color?>? overlayColor,
    double? splashRadius,
    FocusNode? focusNode,
    bool autofocus = false,
    OutlinedBorder? shape,
    BorderSide? side,
    bool isError = false,
    String? semanticLabel,
  }) {
    return LayoutWidgetHelper.paddingField(
      child: Checkbox(
        key: key,
        value: value,
        tristate: tristate,
        onChanged: onChanged,
        mouseCursor: mouseCursor,
        activeColor: activeColor,
        fillColor: CheckboxStyleHelper.primary(context),
        checkColor: checkColor,
        focusColor: focusColor,
        hoverColor: hoverColor,
        overlayColor: overlayColor,
        splashRadius: splashRadius,
        materialTapTargetSize: materialTapTargetSize,
        // visualDensity: visualDensity,
        focusNode: focusNode,
        autofocus: autofocus,
        shape: shape,
        side: side,
        isError: isError,
        semanticLabel: semanticLabel,
      ),
    );
  }

  static Widget secondary({
    required BuildContext context,
    Key? key,
    required bool? value,
    required ValueChanged<bool?>? onChanged,
    MouseCursor? mouseCursor,
    Color? activeColor,
    // WidgetStateProperty<Color?>? fillColor,
    Color? checkColor,
    bool tristate = false,
    MaterialTapTargetSize? materialTapTargetSize,
    ty,
    Color? focusColor,
    Color? hoverColor,
    WidgetStateProperty<Color?>? overlayColor,
    double? splashRadius,
    FocusNode? focusNode,
    bool autofocus = false,
    OutlinedBorder? shape,
    BorderSide? side,
    bool isError = false,
    String? semanticLabel,
  }) {
    return LayoutWidgetHelper.paddingField(
      child: Checkbox(
        key: key,
        value: value,
        tristate: tristate,
        onChanged: onChanged,
        mouseCursor: mouseCursor,
        activeColor: activeColor,
        fillColor: CheckboxStyleHelper.transparent(),
        checkColor: CheckboxStyleHelper.secondaryColor(context),
        focusColor: focusColor,
        hoverColor: hoverColor,
        overlayColor: overlayColor,
        splashRadius: splashRadius,
        materialTapTargetSize: materialTapTargetSize,
        // visualDensity: visualDensity,
        focusNode: focusNode,
        autofocus: autofocus,
        shape: shape,
        side: CheckboxStyleHelper.secondarySide(context),
        isError: isError,
        semanticLabel: semanticLabel,
      ),
    );
  }

  static Widget tertiary({
    required BuildContext context,
    Key? key,
    required bool? value,
    required ValueChanged<bool?>? onChanged,
    MouseCursor? mouseCursor,
    Color? activeColor,
    // WidgetStateProperty<Color?>? fillColor,
    Color? checkColor,
    bool tristate = false,
    MaterialTapTargetSize? materialTapTargetSize,
    ty,
    Color? focusColor,
    Color? hoverColor,
    WidgetStateProperty<Color?>? overlayColor,
    double? splashRadius,
    FocusNode? focusNode,
    bool autofocus = false,
    OutlinedBorder? shape,
    BorderSide? side,
    bool isError = false,
    String? semanticLabel,
  }) {
    return LayoutWidgetHelper.paddingField(
      child: Checkbox(
        key: key,
        value: value,
        tristate: tristate,
        onChanged: onChanged,
        mouseCursor: mouseCursor,
        activeColor: activeColor,
        fillColor: CheckboxStyleHelper.transparent(),
        checkColor: CheckboxStyleHelper.secondaryColor(context),
        focusColor: focusColor,
        hoverColor: hoverColor,
        overlayColor: overlayColor,
        splashRadius: splashRadius,
        materialTapTargetSize: materialTapTargetSize,
        // visualDensity: visualDensity,
        focusNode: focusNode,
        autofocus: autofocus,
        shape: shape,
        side: CheckboxStyleHelper.tertiarySide(),
        isError: isError,
        semanticLabel: semanticLabel,
      ),
    );
  }
}
