part of '../field.dart';

class PmsTextField {
  static Widget primary({
    Key? key,
    //Object groupId = EditableText,
    String? initialValue,
    FocusNode? focusNode,
    String? forceErrorText,
    InputDecoration? decoration = const InputDecoration(),
    TextInputType? keyboardType,
    TextCapitalization textCapitalization = TextCapitalization.none,
    TextInputAction? textInputAction,
    TextStyle? style,
    StrutStyle? strutStyle,
    TextDirection? textDirection,
    TextAlign textAlign = TextAlign.start,
    TextAlignVertical? textAlignVertical,
    bool autofocus = false,
    bool readOnly = false,
    bool? showCursor,
    String obscuringCharacter = '•',
    bool obscureText = false,
    bool autocorrect = true,
    SmartDashesType? smartDashesType,
    SmartQuotesType? smartQuotesType,
    bool enableSuggestions = true,
    MaxLengthEnforcement? maxLengthEnforcement,
    int? maxLines = 1,
    int? minLines,
    bool expands = false,
    int? maxLength,
    ValueChanged<String>? onChanged,
    GestureTapCallback? onTap,
    bool onTapAlwaysCalled = false,
    TapRegionCallback? onTapOutside,
    TapRegionUpCallback? onTapUpOutside,
    VoidCallback? onEditingComplete,
    ValueChanged<String>? onFieldSubmitted,
    VoidCallback? onSaved,
    FormFieldErrorBuilder? errorBuilder,
    List<TextInputFormatter>? inputFormatters,
    bool? enabled,
    bool? ignorePointers,
    double cursorWidth = 2.0,
    double? cursorHeight,
    Radius? cursorRadius,
    Color? cursorColor,
    Color? cursorErrorColor,
    Brightness? keyboardAppearance,
    EdgeInsets scrollPadding = const EdgeInsets.all(20.0),
    bool? enableInteractiveSelection,
    bool? selectAllOnFocus,
    TextSelectionControls? selectionControls,
    InputCounterWidgetBuilder? buildCounter,
    ScrollPhysics? scrollPhysics,
    Iterable<String>? autofillHints,
    AutovalidateMode? autovalidateMode,
    ScrollController? scrollController,
    bool enableIMEPersonalizedLearning = true,
    MouseCursor? mouseCursor,
    SpellCheckConfiguration? spellCheckConfiguration,
    TextMagnifierConfiguration? magnifierConfiguration,
    UndoHistoryController? undoController,
    AppPrivateCommandCallback? onAppPrivateCommand,
    bool? cursorOpacityAnimates,
    ContentInsertionConfiguration? contentInsertionConfiguration,
    Clip clipBehavior = Clip.hardEdge,
    Widget? label,
    Widget? hint,
    Duration? hintDuration,
    bool scribbleEnabled = true,
    bool stylusHandwritingEnabled =
        EditableText.defaultStylusHandwritingEnabled,
    bool canRequestFocus = true,
    List<Locale>? hintLocales,
    Icon? suffixIcon,
    Icon? prefixIcon,
  }) {
    return LayoutWidgetHelper.paddingField(
      child: TextFormField(
        key: key,
        //groupId: groupId,
        focusNode: focusNode,
        decoration: InputDecoration(
          border: InputTextStyleHelper.primary(),
          suffixIcon: suffixIcon,
          prefixIcon: prefixIcon,
          label: label,
          hint: hint,
          hintFadeDuration: hintDuration,
          contentPadding: EdgeInsets.symmetric(
            horizontal: InputFieldConstant.PADDING_H,
          ),
        ),
        keyboardType: keyboardType,
        textInputAction: textInputAction,
        style: style,
        strutStyle: strutStyle,
        textAlign: textAlign,
        textAlignVertical: textAlignVertical,
        textDirection: textDirection,
        textCapitalization: textCapitalization,
        autofocus: autofocus,
        readOnly: readOnly,
        showCursor: showCursor,
        obscuringCharacter: obscuringCharacter,
        obscureText: obscureText,
        autocorrect: autocorrect,
        smartDashesType:
            smartDashesType ??
            (obscureText ? SmartDashesType.disabled : SmartDashesType.enabled),
        smartQuotesType:
            smartQuotesType ??
            (obscureText ? SmartQuotesType.disabled : SmartQuotesType.enabled),
        enableSuggestions: enableSuggestions,
        maxLengthEnforcement: maxLengthEnforcement,
        maxLines: maxLines,
        minLines: minLines,
        expands: expands,
        maxLength: maxLength,
        onChanged: onChanged,
        onTap: onTap,
        onTapAlwaysCalled: onTapAlwaysCalled,
        onTapOutside: onTapOutside,
        onTapUpOutside: onTapUpOutside,
        onEditingComplete: onEditingComplete,
        inputFormatters: inputFormatters,
        enabled: enabled ?? decoration?.enabled ?? true,
        ignorePointers: ignorePointers,
        cursorWidth: cursorWidth,
        cursorHeight: cursorHeight,
        cursorRadius: cursorRadius,
        cursorColor: cursorColor,
        cursorErrorColor: cursorErrorColor,
        scrollPadding: scrollPadding,
        scrollPhysics: scrollPhysics,
        keyboardAppearance: keyboardAppearance,
        enableInteractiveSelection:
            enableInteractiveSelection ?? (!obscureText || !readOnly),
        selectAllOnFocus: selectAllOnFocus,
        selectionControls: selectionControls,
        buildCounter: buildCounter,
        autofillHints: autofillHints,
        scrollController: scrollController,
        enableIMEPersonalizedLearning: enableIMEPersonalizedLearning,
        mouseCursor: mouseCursor,
        spellCheckConfiguration: spellCheckConfiguration,
        magnifierConfiguration: magnifierConfiguration,
        undoController: undoController,
        onAppPrivateCommand: onAppPrivateCommand,
        cursorOpacityAnimates: cursorOpacityAnimates,
      ),
    );
  }
}
