\c test_avocado
GRANT ALL ON ALL SEQUENCES IN SCHEMA tests TO tester_admin;
GRANT ALL ON ALL FUNCTIONS IN SCHEMA tests TO tester_admin;
GRANT ALL ON ALL TABLES IN SCHEMA tests TO tester_admin;

GRANT CREATE ON DATABASE test_avocado TO tester_admin;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA tests TO tester_admin;
GRANT SELECT,UPDATE,DELETE ON ALL TABLES IN SCHEMA  tests TO tester;