# department_category画面 - Edit(ミューテーション)
#
# 画面仕様: source/view.yaml #DepartmentCategoryEdit(組織区分、info_department_kind_value)

mutation DepartmentCategoryEdit(
  $infoDepartmentKindValueId: UUID!
  $remarks: String
  $sharedAppellationsId: UUID!
  $jaLanguageCodeId: UUID!
  $enLanguageCodeId: UUID!
  $nameSharedDictionaryId: UUID!
  $nameJa: String!
  $nameEn: String!
  $pronunciationSharedDictionaryId: UUID!
  $pronunciationJa: String!
  $pronunciationEn: String!
  $nicknameSharedDictionaryId: UUID!
  $nicknameJa: String!
  $nicknameEn: String!
) {
  updateInfoDepartmentKindValueByInfoDepartmentKindValueId(
    input: {
      infoDepartmentKindValueId: $infoDepartmentKindValueId
      infoDepartmentKindValuePatch: {
        remarks: $remarks

        sharedAppellationToSharedAppellationsId: {
          updateBySharedAppellationsId: {
            sharedAppellationsId: $sharedAppellationsId
            sharedAppellationPatch: {
              sharedDictionaryToSharedDictionaryNameId: {
                updateBySharedDictionaryId: {
                  sharedDictionaryId: $nameSharedDictionaryId
                  sharedDictionaryPatch: {
                    sharedDictionaryValuesUsingSharedDictionaryId: {
                      deleteOthers: true
                      create: [
                        { sharedLanguageCodeId: $jaLanguageCodeId, dictionaryValue: $nameJa }
                        { sharedLanguageCodeId: $enLanguageCodeId, dictionaryValue: $nameEn }
                      ]
                    }
                  }
                }
              }
              sharedDictionaryToSharedDictionaryPronunciationId: {
                updateBySharedDictionaryId: {
                  sharedDictionaryId: $pronunciationSharedDictionaryId
                  sharedDictionaryPatch: {
                    sharedDictionaryValuesUsingSharedDictionaryId: {
                      deleteOthers: true
                      create: [
                        { sharedLanguageCodeId: $jaLanguageCodeId, dictionaryValue: $pronunciationJa }
                        { sharedLanguageCodeId: $enLanguageCodeId, dictionaryValue: $pronunciationEn }
                      ]
                    }
                  }
                }
              }
              sharedDictionaryToSharedDictionaryNicknameId: {
                updateBySharedDictionaryId: {
                  sharedDictionaryId: $nicknameSharedDictionaryId
                  sharedDictionaryPatch: {
                    sharedDictionaryValuesUsingSharedDictionaryId: {
                      deleteOthers: true
                      create: [
                        { sharedLanguageCodeId: $jaLanguageCodeId, dictionaryValue: $nicknameJa }
                        { sharedLanguageCodeId: $enLanguageCodeId, dictionaryValue: $nicknameEn }
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  ) {
    infoDepartmentKindValue {
      infoDepartmentKindValueId
      remarks
      labels: sharedAppellationBySharedAppellationsId {
        sharedAppellationsId
        sharedDictionaryBySharedDictionaryNameId {
          sharedDictionaryId
          ja: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $jaLanguageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
          en: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $enLanguageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
        }
        sharedDictionaryBySharedDictionaryPronunciationId {
          sharedDictionaryId
          ja: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $jaLanguageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
          en: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $enLanguageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
        }
        sharedDictionaryBySharedDictionaryNicknameId {
          sharedDictionaryId
          ja: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $jaLanguageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
          en: sharedDictionaryValuesBySharedDictionaryId(
            condition: { sharedLanguageCodeId: $enLanguageCodeId }
          ) {
            nodes {
              dictionaryValue
            }
          }
        }
      }
    }
  }
}
