part of '../ut_field.dart';

class UtDropdownField {
  static Widget primary<T>({
    Key? key,
    required List<DropdownMenuItem<T>>? items,
    DropdownButtonBuilder? selectedItemBuilder,
    @Deprecated(
      'Use initialValue instead. '
      'This will set the initial value for the form field. '
      'This feature was deprecated after v3.33.0-1.0.pre.',
    )
    T? value,
    T? initialValue,
    Widget? hint,
    Widget? disabledHint,
    required ValueChanged<T?>? onChanged,
    VoidCallback? onTap,
    int elevation = 8,
    TextStyle? style,
    Widget? icon,
    Color? iconDisabledColor,
    Color? iconEnabledColor,
    double iconSize = 24.0,
    bool isDense = true,
    bool isExpanded = false,
    double? itemHeight,
    Color? focusColor,
    FocusNode? focusNode,
    bool autofocus = false,
    Color? dropdownColor,
    InputDecoration? decoration,
    FormFieldSetter<T>? onSaved,
    FormFieldValidator<T>? validator,
    FormFieldErrorBuilder? errorBuilder,
    String? forceErrorText,
    AutovalidateMode? autovalidateMode,
    double? menuMaxHeight,
    bool? enableFeedback,
    AlignmentGeometry alignment = AlignmentDirectional.centerStart,
    BorderRadius? borderRadius,
    EdgeInsetsGeometry? padding,
    bool barrierDismissible = true,
    Widget? label,
    Duration? hintDuration,
    Icon? prefixIcon,
  }) {
    return UtLayoutWidgetHelper.paddingField(
      child: DropdownButtonFormField<T>(
        key: key,
        items: items,
        selectedItemBuilder: selectedItemBuilder,
        initialValue: initialValue,
        hint: hint,
        disabledHint: disabledHint,
        onChanged: onChanged,
        onTap: onTap,
        elevation: elevation,
        style: style,
        icon: icon,
        iconDisabledColor: iconDisabledColor,
        iconEnabledColor: iconEnabledColor,
        iconSize: iconSize,
        isDense: isDense,
        isExpanded: isExpanded,
        itemHeight: itemHeight,
        focusColor: focusColor,
        focusNode: focusNode,
        autofocus: autofocus,
        dropdownColor: dropdownColor,
        decoration: InputDecoration(
          border: InputTextStyleHelper.primary(),
          // suffixIcon: suffixIcon,
          prefixIcon: prefixIcon,
          label: label,
          hint: hint,
          hintFadeDuration: hintDuration,
          contentPadding: EdgeInsets.symmetric(
            horizontal: UtInputFieldConstant.PADDING_H,
          ),
        ),
        onSaved: onSaved,
        validator: validator,
        errorBuilder: errorBuilder,
        forceErrorText: forceErrorText,
        autovalidateMode: autovalidateMode,
        menuMaxHeight: menuMaxHeight,
        enableFeedback: enableFeedback,
        alignment: alignment,
        borderRadius: borderRadius,
        padding: padding,
        barrierDismissible: barrierDismissible = true,
      ),
    );
  }
}
