part of '../ut_field.dart';

class UtRadioField {
  static Widget primary<T>({
    Key? key,
    required T value,
    MouseCursor? mouseCursor,
    bool toggleable = false,
    Color? activeColor,
    WidgetStateProperty<Color?>? fillColor,
    Color? hoverColor,
    WidgetStateProperty<Color?>? overlayColor,
    double? splashRadius,
    MaterialTapTargetSize? materialTapTargetSize,
    Widget? title,
    Widget? subtitle,
    Widget? secondary,
    bool? isThreeLine,
    bool? dense,
    bool selected = false,
    ListTileControlAffinity? controlAffinity,
    bool autofocus = false,
    EdgeInsetsGeometry? contentPadding,
    ShapeBorder? shape,
    Color? tileColor,
    Color? selectedTileColor,
    VisualDensity? visualDensity,
    FocusNode? focusNode,
    ValueChanged<bool>? onFocusChange,
    bool? enableFeedback,
    ListTileTitleAlignment? titleAlignment,
    bool internalAddSemanticForOnTap = true,
    bool useCupertinoCheckmarkStyle = false,
    double radioScaleFactor = 1.0,
    bool? enabled,
    WidgetStateProperty<Color?>? radioBackgroundColor,
    BorderSide? radioSide,
    WidgetStateProperty<double?>? radioInnerRadius,
  }) {
    return UtLayoutWidgetHelper.paddingField(
      child: RadioListTile(
        key: key,
        value: value,
        mouseCursor: mouseCursor,
        toggleable: toggleable = false,
        activeColor: activeColor,
        fillColor: fillColor,
        hoverColor: hoverColor,
        overlayColor: overlayColor,
        splashRadius: splashRadius,
        materialTapTargetSize: materialTapTargetSize,
        title: title,
        subtitle: subtitle,
        isThreeLine: isThreeLine,
        dense: dense,
        secondary: secondary,
        selected: selected,
        controlAffinity: controlAffinity,
        autofocus: autofocus,
        contentPadding: contentPadding,
        shape: shape,
        tileColor: tileColor,
        selectedTileColor: selectedTileColor,
        visualDensity: visualDensity,
        focusNode: focusNode,
        onFocusChange: onFocusChange,
        enableFeedback: enableFeedback,
        radioScaleFactor: radioScaleFactor,
        titleAlignment: titleAlignment,
        enabled: enabled,
        internalAddSemanticForOnTap: internalAddSemanticForOnTap,
        radioBackgroundColor: radioBackgroundColor,
        radioSide: radioSide,
        radioInnerRadius: radioInnerRadius,
      ),
    );
  }
}
